### ISSUE TITLE
build stack migration, app structure reshape, docs

### ISSUE THREAD

**Issue by oleksmarkh** [Kosmosnimki/crisismap#1]
# Motivation

* streamline and simplify modules orchestration and data fetch
* upgrade deps themselves, removing superfluous ones, list deps explicitly in `package.json`
* enable the build tool to chunk, compress and hash assets <- `webpack` has those features out of the box
* use more concise and functional approach to data transformations and wiring
* describe the app itself in some form of `README.md`

# Prerequisites

* all legacy `GMX<...>` deps and traces are deprecated

# Setup/rework

* see https://github.com/Crisismap/crisismap-frontend/issues/1

**Comment by oleksmarkh** [comment]
as agreed, a new repo is set up, as a pass to deprecation of this one 🔢

**Comment by zverev** [comment]
@oleksmarkh 
Where is it located?

**Comment by oleksmarkh** [comment]
@zverev, just created: https://github.com/Crisismap/crirismap-frontend
